// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "users/v1/GuildShardingConfig.proto" (package "discord_protos.users.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * @generated from protobuf message discord_protos.users.v1.GuildShardingConfig
 */
export interface GuildShardingConfig {
    /**
     * @generated from protobuf field: repeated int32 shards = 1
     */
    shards: number[];
}
// @generated message type with reflection information, may provide speed optimized methods
class GuildShardingConfig$Type extends MessageType<GuildShardingConfig> {
    constructor() {
        super("discord_protos.users.v1.GuildShardingConfig", [
            { no: 1, name: "shards", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 5 /*ScalarType.INT32*/ }
        ]);
    }
    create(value?: PartialMessage<GuildShardingConfig>): GuildShardingConfig {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.shards = [];
        if (value !== undefined)
            reflectionMergePartial<GuildShardingConfig>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GuildShardingConfig): GuildShardingConfig {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated int32 shards */ 1:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.shards.push(reader.int32());
                    else
                        message.shards.push(reader.int32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GuildShardingConfig, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated int32 shards = 1; */
        if (message.shards.length) {
            writer.tag(1, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.shards.length; i++)
                writer.int32(message.shards[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.GuildShardingConfig
 */
export const GuildShardingConfig = new GuildShardingConfig$Type();
