// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "users/v1/MediumUser.proto" (package "discord_protos.users.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { StringValue } from "../../google/protobuf/wrappers";
/**
 * @generated from protobuf message discord_protos.users.v1.MediumUser
 */
export interface MediumUser {
    /**
     * @generated from protobuf field: fixed64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: string username = 2
     */
    username: string;
    /**
     * @generated from protobuf field: uint32 discriminator = 3
     */
    discriminator: number;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue avatar_hash = 4
     */
    avatarHash?: StringValue;
    /**
     * @generated from protobuf field: bool bot = 5
     */
    bot: boolean;
    /**
     * @generated from protobuf field: uint64 flags = 6
     */
    flags: bigint;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue email = 7
     */
    email?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue phone = 8
     */
    phone?: StringValue;
}
// @generated message type with reflection information, may provide speed optimized methods
class MediumUser$Type extends MessageType<MediumUser> {
    constructor() {
        super("discord_protos.users.v1.MediumUser", [
            { no: 1, name: "id", kind: "scalar", T: 6 /*ScalarType.FIXED64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "discriminator", kind: "scalar", T: 13 /*ScalarType.UINT32*/ },
            { no: 4, name: "avatar_hash", kind: "message", T: () => StringValue },
            { no: 5, name: "bot", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "flags", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 7, name: "email", kind: "message", T: () => StringValue },
            { no: 8, name: "phone", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<MediumUser>): MediumUser {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.username = "";
        message.discriminator = 0;
        message.bot = false;
        message.flags = 0n;
        if (value !== undefined)
            reflectionMergePartial<MediumUser>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: MediumUser): MediumUser {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* fixed64 id */ 1:
                    message.id = reader.fixed64().toBigInt();
                    break;
                case /* string username */ 2:
                    message.username = reader.string();
                    break;
                case /* uint32 discriminator */ 3:
                    message.discriminator = reader.uint32();
                    break;
                case /* optional google.protobuf.StringValue avatar_hash */ 4:
                    message.avatarHash = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.avatarHash);
                    break;
                case /* bool bot */ 5:
                    message.bot = reader.bool();
                    break;
                case /* uint64 flags */ 6:
                    message.flags = reader.uint64().toBigInt();
                    break;
                case /* optional google.protobuf.StringValue email */ 7:
                    message.email = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.email);
                    break;
                case /* optional google.protobuf.StringValue phone */ 8:
                    message.phone = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.phone);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: MediumUser, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* fixed64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Bit64).fixed64(message.id);
        /* string username = 2; */
        if (message.username !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.username);
        /* uint32 discriminator = 3; */
        if (message.discriminator !== 0)
            writer.tag(3, WireType.Varint).uint32(message.discriminator);
        /* optional google.protobuf.StringValue avatar_hash = 4; */
        if (message.avatarHash)
            StringValue.internalBinaryWrite(message.avatarHash, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* bool bot = 5; */
        if (message.bot !== false)
            writer.tag(5, WireType.Varint).bool(message.bot);
        /* uint64 flags = 6; */
        if (message.flags !== 0n)
            writer.tag(6, WireType.Varint).uint64(message.flags);
        /* optional google.protobuf.StringValue email = 7; */
        if (message.email)
            StringValue.internalBinaryWrite(message.email, writer.tag(7, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue phone = 8; */
        if (message.phone)
            StringValue.internalBinaryWrite(message.phone, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.MediumUser
 */
export const MediumUser = new MediumUser$Type();
