// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "users/v1/User.proto" (package "discord_protos.users.v1", syntax proto3)
// tslint:disable
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
import { Timestamp } from "../../google/protobuf/timestamp";
import { BoolValue } from "../../google/protobuf/wrappers";
import { UInt32Value } from "../../google/protobuf/wrappers";
import { UInt64Value } from "../../google/protobuf/wrappers";
import { StringValue } from "../../google/protobuf/wrappers";
/**
 * @generated from protobuf message discord_protos.users.v1.User
 */
export interface User {
    /**
     * @generated from protobuf field: uint64 id = 1
     */
    id: bigint;
    /**
     * @generated from protobuf field: string username = 2
     */
    username: string;
    /**
     * @generated from protobuf field: string discriminator = 3
     */
    discriminator: string;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue avatar = 4
     */
    avatar?: StringValue;
    /**
     * @generated from protobuf field: bool bot = 5
     */
    bot: boolean;
    /**
     * @generated from protobuf field: uint64 public_flags = 6
     */
    publicFlags: bigint;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue global_name = 8
     */
    globalName?: StringValue;
    /**
     * @generated from protobuf field: optional discord_protos.users.v1.User.UserAvatarDecoration avatar_decoration_data = 9
     */
    avatarDecorationData?: User_UserAvatarDecoration;
    /**
     * @generated from protobuf field: optional discord_protos.users.v1.User.UserPrimaryGuild primary_guild = 10
     */
    primaryGuild?: User_UserPrimaryGuild;
    /**
     * @generated from protobuf field: optional discord_protos.users.v1.User.UserCollectibles collectibles = 11
     */
    collectibles?: User_UserCollectibles;
    /**
     * @generated from protobuf field: optional discord_protos.users.v1.User.SafetyState safety_state = 12
     */
    safetyState?: User_SafetyState;
    /**
     * @generated from protobuf field: optional discord_protos.users.v1.User.DisplayNameStyles display_name_styles = 13
     */
    displayNameStyles?: User_DisplayNameStyles;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.UserAvatarDecoration
 */
export interface User_UserAvatarDecoration {
    /**
     * @generated from protobuf field: string asset = 1
     */
    asset: string;
    /**
     * @generated from protobuf field: optional google.protobuf.UInt64Value sku_id = 2
     */
    skuId?: UInt64Value;
    /**
     * @generated from protobuf field: optional google.protobuf.UInt32Value expires_at = 3
     */
    expiresAt?: UInt32Value;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.UserPrimaryGuild
 */
export interface User_UserPrimaryGuild {
    /**
     * @generated from protobuf field: optional google.protobuf.UInt64Value identity_guild_id = 1
     */
    identityGuildId?: UInt64Value;
    /**
     * @generated from protobuf field: optional google.protobuf.BoolValue identity_enabled = 2
     */
    identityEnabled?: BoolValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue tag = 3
     */
    tag?: StringValue;
    /**
     * @generated from protobuf field: optional google.protobuf.StringValue badge = 4
     */
    badge?: StringValue;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.UserNameplate
 */
export interface User_UserNameplate {
    /**
     * @generated from protobuf field: string asset = 1
     */
    asset: string;
    /**
     * @generated from protobuf field: string palette = 2
     */
    palette: string;
    /**
     * @generated from protobuf field: optional google.protobuf.UInt64Value sku_id = 3
     */
    skuId?: UInt64Value;
    /**
     * @generated from protobuf field: optional google.protobuf.Timestamp expires_at = 4
     */
    expiresAt?: Timestamp;
    /**
     * @generated from protobuf field: string label = 5
     */
    label: string;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.UserCollectibles
 */
export interface User_UserCollectibles {
    /**
     * @generated from protobuf field: optional discord_protos.users.v1.User.UserNameplate nameplate = 1
     */
    nameplate?: User_UserNameplate;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.NormalState
 */
export interface User_NormalState {
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.RestrictedState
 */
export interface User_RestrictedState {
    /**
     * @generated from protobuf field: optional google.protobuf.Timestamp restricted_until = 1
     */
    restrictedUntil?: Timestamp;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.DeferredActionState
 */
export interface User_DeferredActionState {
    /**
     * @generated from protobuf field: optional google.protobuf.Timestamp action_deferred_until = 1
     */
    actionDeferredUntil?: Timestamp;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.TempBannedState
 */
export interface User_TempBannedState {
    /**
     * @generated from protobuf field: optional google.protobuf.Timestamp banned_until = 1
     */
    bannedUntil?: Timestamp;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.BannedState
 */
export interface User_BannedState {
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.SafetyState
 */
export interface User_SafetyState {
    /**
     * @generated from protobuf oneof: state
     */
    state: {
        oneofKind: "normal";
        /**
         * @generated from protobuf field: discord_protos.users.v1.User.NormalState normal = 101
         */
        normal: User_NormalState;
    } | {
        oneofKind: "restricted";
        /**
         * @generated from protobuf field: discord_protos.users.v1.User.RestrictedState restricted = 102
         */
        restricted: User_RestrictedState;
    } | {
        oneofKind: "deferredAction";
        /**
         * @generated from protobuf field: discord_protos.users.v1.User.DeferredActionState deferred_action = 103
         */
        deferredAction: User_DeferredActionState;
    } | {
        oneofKind: "tempBanned";
        /**
         * @generated from protobuf field: discord_protos.users.v1.User.TempBannedState temp_banned = 104
         */
        tempBanned: User_TempBannedState;
    } | {
        oneofKind: "banned";
        /**
         * @generated from protobuf field: discord_protos.users.v1.User.BannedState banned = 105
         */
        banned: User_BannedState;
    } | {
        oneofKind: undefined;
    };
    /**
     * @generated from protobuf field: discord_protos.users.v1.User.SafetyStateReason reason = 1
     */
    reason: User_SafetyStateReason;
    /**
     * @generated from protobuf field: repeated discord_protos.users.v1.User.SafetyAnnotations annotations = 2
     */
    annotations: User_SafetyAnnotations[];
    /**
     * @generated from protobuf field: optional google.protobuf.UInt64Value last_mutation_id = 3
     */
    lastMutationId?: UInt64Value;
}
/**
 * @generated from protobuf message discord_protos.users.v1.User.DisplayNameStyles
 */
export interface User_DisplayNameStyles {
    /**
     * @generated from protobuf field: discord_protos.users.v1.User.DisplayNameFont font_id = 1
     */
    fontId: User_DisplayNameFont;
    /**
     * @generated from protobuf field: discord_protos.users.v1.User.DisplayNameEffect effect_id = 2
     */
    effectId: User_DisplayNameEffect;
    /**
     * @generated from protobuf field: repeated uint32 colors = 3
     */
    colors: number[];
}
/**
 * @generated from protobuf enum discord_protos.users.v1.User.SafetyStateReason
 */
export enum User_SafetyStateReason {
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_REASON_UNSPECIFIED = 0;
     */
    REASON_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_DISABLED_SUSPICIOUS_ACTIVITY = 1;
     */
    DISABLED_SUSPICIOUS_ACTIVITY = 1,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_SMITE_REMOVE_EMAIL_VERIFICATION = 2;
     */
    SMITE_REMOVE_EMAIL_VERIFICATION = 2,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_USER_REQUIRED_VERIFICATION_INTERVENTIONS_CLIENT = 3;
     */
    USER_REQUIRED_VERIFICATION_INTERVENTIONS_CLIENT = 3,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_ACTIVE_ASSIGNMENT_COMPLETED = 4;
     */
    ACTIVE_ASSIGNMENT_COMPLETED = 4,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_ACTIVE_ASSIGNMENT_CREATED = 5;
     */
    ACTIVE_ASSIGNMENT_CREATED = 5,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_DEFERRED_ASSIGNMENT_CREATED = 6;
     */
    DEFERRED_ASSIGNMENT_CREATED = 6,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_DEFERRED_ASSIGNMENT_UPGRADED_TO_ACTIVE = 7;
     */
    DEFERRED_ASSIGNMENT_UPGRADED_TO_ACTIVE = 7,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_DEFERRED_ASSIGNMENT_CANCELLED = 8;
     */
    DEFERRED_ASSIGNMENT_CANCELLED = 8,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_ASSIGNMENT_STATE_REPAIRED = 9;
     */
    ASSIGNMENT_STATE_REPAIRED = 9,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_MANUAL_PERMANENT_BAN = 10;
     */
    MANUAL_PERMANENT_BAN = 10,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_SAFETY_SYSTEM_UNBAN = 11;
     */
    SAFETY_SYSTEM_UNBAN = 11,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_GENERIC_AUTOMATED_SAFETY_ACTION = 12;
     */
    GENERIC_AUTOMATED_SAFETY_ACTION = 12,
    /**
     * @generated from protobuf enum value: SAFETY_STATE_REASON_GENERIC_MANUAL_SAFETY_ACTION = 13;
     */
    GENERIC_MANUAL_SAFETY_ACTION = 13
}
/**
 * @generated from protobuf enum discord_protos.users.v1.User.SafetyAnnotations
 */
export enum User_SafetyAnnotations {
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_ANNOTATION_UNSPECIFIED = 0;
     */
    ANNOTATION_UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_SPAMMER = 1;
     */
    SPAMMER = 1,
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_SELF_DELETED = 2;
     */
    SELF_DELETED = 2,
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_SELF_DISABLED = 3;
     */
    SELF_DISABLED = 3,
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_UNDERAGE_DELETED = 4;
     */
    UNDERAGE_DELETED = 4,
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_SAFETY_POLICY_VIOLATION = 5;
     */
    SAFETY_POLICY_VIOLATION = 5,
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_INACTIVITY_DELETED = 6;
     */
    INACTIVITY_DELETED = 6,
    /**
     * @generated from protobuf enum value: SAFETY_ANNOTATIONS_GENERIC_DELETED = 7;
     */
    GENERIC_DELETED = 7
}
/**
 * @generated from protobuf enum discord_protos.users.v1.User.DisplayNameFont
 */
export enum User_DisplayNameFont {
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_DEFAULT = 11;
     */
    DEFAULT = 11,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_BANGERS = 1;
     */
    BANGERS = 1,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_BIO_RHYME = 2;
     */
    BIO_RHYME = 2,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_CHERRY_BOMB = 3;
     */
    CHERRY_BOMB = 3,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_CHICLE = 4;
     */
    CHICLE = 4,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_COMPAGNON = 5;
     */
    COMPAGNON = 5,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_MUSEO_MODERNO = 6;
     */
    MUSEO_MODERNO = 6,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_NEO_CASTEL = 7;
     */
    NEO_CASTEL = 7,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_PIXELIFY = 8;
     */
    PIXELIFY = 8,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_RIBES = 9;
     */
    RIBES = 9,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_SINISTRE = 10;
     */
    SINISTRE = 10,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_FONT_ZILLA_SLAB = 12;
     */
    ZILLA_SLAB = 12
}
/**
 * @generated from protobuf enum discord_protos.users.v1.User.DisplayNameEffect
 */
export enum User_DisplayNameEffect {
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_EFFECT_UNSPECIFIED = 0;
     */
    UNSPECIFIED = 0,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_EFFECT_SOLID = 1;
     */
    SOLID = 1,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_EFFECT_GRADIENT = 2;
     */
    GRADIENT = 2,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_EFFECT_NEON = 3;
     */
    NEON = 3,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_EFFECT_TOON = 4;
     */
    TOON = 4,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_EFFECT_POP = 5;
     */
    POP = 5,
    /**
     * @generated from protobuf enum value: DISPLAY_NAME_EFFECT_GLOW = 6;
     */
    GLOW = 6
}
// @generated message type with reflection information, may provide speed optimized methods
class User$Type extends MessageType<User> {
    constructor() {
        super("discord_protos.users.v1.User", [
            { no: 1, name: "id", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "discriminator", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 4, name: "avatar", kind: "message", T: () => StringValue },
            { no: 5, name: "bot", kind: "scalar", T: 8 /*ScalarType.BOOL*/ },
            { no: 6, name: "public_flags", kind: "scalar", T: 4 /*ScalarType.UINT64*/, L: 0 /*LongType.BIGINT*/ },
            { no: 8, name: "global_name", kind: "message", T: () => StringValue },
            { no: 9, name: "avatar_decoration_data", kind: "message", T: () => User_UserAvatarDecoration },
            { no: 10, name: "primary_guild", kind: "message", T: () => User_UserPrimaryGuild },
            { no: 11, name: "collectibles", kind: "message", T: () => User_UserCollectibles },
            { no: 12, name: "safety_state", kind: "message", T: () => User_SafetyState },
            { no: 13, name: "display_name_styles", kind: "message", T: () => User_DisplayNameStyles }
        ]);
    }
    create(value?: PartialMessage<User>): User {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.id = 0n;
        message.username = "";
        message.discriminator = "";
        message.bot = false;
        message.publicFlags = 0n;
        if (value !== undefined)
            reflectionMergePartial<User>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User): User {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* uint64 id */ 1:
                    message.id = reader.uint64().toBigInt();
                    break;
                case /* string username */ 2:
                    message.username = reader.string();
                    break;
                case /* string discriminator */ 3:
                    message.discriminator = reader.string();
                    break;
                case /* optional google.protobuf.StringValue avatar */ 4:
                    message.avatar = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.avatar);
                    break;
                case /* bool bot */ 5:
                    message.bot = reader.bool();
                    break;
                case /* uint64 public_flags */ 6:
                    message.publicFlags = reader.uint64().toBigInt();
                    break;
                case /* optional google.protobuf.StringValue global_name */ 8:
                    message.globalName = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.globalName);
                    break;
                case /* optional discord_protos.users.v1.User.UserAvatarDecoration avatar_decoration_data */ 9:
                    message.avatarDecorationData = User_UserAvatarDecoration.internalBinaryRead(reader, reader.uint32(), options, message.avatarDecorationData);
                    break;
                case /* optional discord_protos.users.v1.User.UserPrimaryGuild primary_guild */ 10:
                    message.primaryGuild = User_UserPrimaryGuild.internalBinaryRead(reader, reader.uint32(), options, message.primaryGuild);
                    break;
                case /* optional discord_protos.users.v1.User.UserCollectibles collectibles */ 11:
                    message.collectibles = User_UserCollectibles.internalBinaryRead(reader, reader.uint32(), options, message.collectibles);
                    break;
                case /* optional discord_protos.users.v1.User.SafetyState safety_state */ 12:
                    message.safetyState = User_SafetyState.internalBinaryRead(reader, reader.uint32(), options, message.safetyState);
                    break;
                case /* optional discord_protos.users.v1.User.DisplayNameStyles display_name_styles */ 13:
                    message.displayNameStyles = User_DisplayNameStyles.internalBinaryRead(reader, reader.uint32(), options, message.displayNameStyles);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* uint64 id = 1; */
        if (message.id !== 0n)
            writer.tag(1, WireType.Varint).uint64(message.id);
        /* string username = 2; */
        if (message.username !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.username);
        /* string discriminator = 3; */
        if (message.discriminator !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.discriminator);
        /* optional google.protobuf.StringValue avatar = 4; */
        if (message.avatar)
            StringValue.internalBinaryWrite(message.avatar, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* bool bot = 5; */
        if (message.bot !== false)
            writer.tag(5, WireType.Varint).bool(message.bot);
        /* uint64 public_flags = 6; */
        if (message.publicFlags !== 0n)
            writer.tag(6, WireType.Varint).uint64(message.publicFlags);
        /* optional google.protobuf.StringValue global_name = 8; */
        if (message.globalName)
            StringValue.internalBinaryWrite(message.globalName, writer.tag(8, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.users.v1.User.UserAvatarDecoration avatar_decoration_data = 9; */
        if (message.avatarDecorationData)
            User_UserAvatarDecoration.internalBinaryWrite(message.avatarDecorationData, writer.tag(9, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.users.v1.User.UserPrimaryGuild primary_guild = 10; */
        if (message.primaryGuild)
            User_UserPrimaryGuild.internalBinaryWrite(message.primaryGuild, writer.tag(10, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.users.v1.User.UserCollectibles collectibles = 11; */
        if (message.collectibles)
            User_UserCollectibles.internalBinaryWrite(message.collectibles, writer.tag(11, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.users.v1.User.SafetyState safety_state = 12; */
        if (message.safetyState)
            User_SafetyState.internalBinaryWrite(message.safetyState, writer.tag(12, WireType.LengthDelimited).fork(), options).join();
        /* optional discord_protos.users.v1.User.DisplayNameStyles display_name_styles = 13; */
        if (message.displayNameStyles)
            User_DisplayNameStyles.internalBinaryWrite(message.displayNameStyles, writer.tag(13, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User
 */
export const User = new User$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_UserAvatarDecoration$Type extends MessageType<User_UserAvatarDecoration> {
    constructor() {
        super("discord_protos.users.v1.User.UserAvatarDecoration", [
            { no: 1, name: "asset", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "sku_id", kind: "message", T: () => UInt64Value },
            { no: 3, name: "expires_at", kind: "message", T: () => UInt32Value }
        ]);
    }
    create(value?: PartialMessage<User_UserAvatarDecoration>): User_UserAvatarDecoration {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.asset = "";
        if (value !== undefined)
            reflectionMergePartial<User_UserAvatarDecoration>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_UserAvatarDecoration): User_UserAvatarDecoration {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string asset */ 1:
                    message.asset = reader.string();
                    break;
                case /* optional google.protobuf.UInt64Value sku_id */ 2:
                    message.skuId = UInt64Value.internalBinaryRead(reader, reader.uint32(), options, message.skuId);
                    break;
                case /* optional google.protobuf.UInt32Value expires_at */ 3:
                    message.expiresAt = UInt32Value.internalBinaryRead(reader, reader.uint32(), options, message.expiresAt);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_UserAvatarDecoration, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string asset = 1; */
        if (message.asset !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.asset);
        /* optional google.protobuf.UInt64Value sku_id = 2; */
        if (message.skuId)
            UInt64Value.internalBinaryWrite(message.skuId, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.UInt32Value expires_at = 3; */
        if (message.expiresAt)
            UInt32Value.internalBinaryWrite(message.expiresAt, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.UserAvatarDecoration
 */
export const User_UserAvatarDecoration = new User_UserAvatarDecoration$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_UserPrimaryGuild$Type extends MessageType<User_UserPrimaryGuild> {
    constructor() {
        super("discord_protos.users.v1.User.UserPrimaryGuild", [
            { no: 1, name: "identity_guild_id", kind: "message", T: () => UInt64Value },
            { no: 2, name: "identity_enabled", kind: "message", T: () => BoolValue },
            { no: 3, name: "tag", kind: "message", T: () => StringValue },
            { no: 4, name: "badge", kind: "message", T: () => StringValue }
        ]);
    }
    create(value?: PartialMessage<User_UserPrimaryGuild>): User_UserPrimaryGuild {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<User_UserPrimaryGuild>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_UserPrimaryGuild): User_UserPrimaryGuild {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.UInt64Value identity_guild_id */ 1:
                    message.identityGuildId = UInt64Value.internalBinaryRead(reader, reader.uint32(), options, message.identityGuildId);
                    break;
                case /* optional google.protobuf.BoolValue identity_enabled */ 2:
                    message.identityEnabled = BoolValue.internalBinaryRead(reader, reader.uint32(), options, message.identityEnabled);
                    break;
                case /* optional google.protobuf.StringValue tag */ 3:
                    message.tag = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.tag);
                    break;
                case /* optional google.protobuf.StringValue badge */ 4:
                    message.badge = StringValue.internalBinaryRead(reader, reader.uint32(), options, message.badge);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_UserPrimaryGuild, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.UInt64Value identity_guild_id = 1; */
        if (message.identityGuildId)
            UInt64Value.internalBinaryWrite(message.identityGuildId, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.BoolValue identity_enabled = 2; */
        if (message.identityEnabled)
            BoolValue.internalBinaryWrite(message.identityEnabled, writer.tag(2, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue tag = 3; */
        if (message.tag)
            StringValue.internalBinaryWrite(message.tag, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.StringValue badge = 4; */
        if (message.badge)
            StringValue.internalBinaryWrite(message.badge, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.UserPrimaryGuild
 */
export const User_UserPrimaryGuild = new User_UserPrimaryGuild$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_UserNameplate$Type extends MessageType<User_UserNameplate> {
    constructor() {
        super("discord_protos.users.v1.User.UserNameplate", [
            { no: 1, name: "asset", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "palette", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "sku_id", kind: "message", T: () => UInt64Value },
            { no: 4, name: "expires_at", kind: "message", T: () => Timestamp },
            { no: 5, name: "label", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<User_UserNameplate>): User_UserNameplate {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.asset = "";
        message.palette = "";
        message.label = "";
        if (value !== undefined)
            reflectionMergePartial<User_UserNameplate>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_UserNameplate): User_UserNameplate {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string asset */ 1:
                    message.asset = reader.string();
                    break;
                case /* string palette */ 2:
                    message.palette = reader.string();
                    break;
                case /* optional google.protobuf.UInt64Value sku_id */ 3:
                    message.skuId = UInt64Value.internalBinaryRead(reader, reader.uint32(), options, message.skuId);
                    break;
                case /* optional google.protobuf.Timestamp expires_at */ 4:
                    message.expiresAt = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.expiresAt);
                    break;
                case /* string label */ 5:
                    message.label = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_UserNameplate, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string asset = 1; */
        if (message.asset !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.asset);
        /* string palette = 2; */
        if (message.palette !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.palette);
        /* optional google.protobuf.UInt64Value sku_id = 3; */
        if (message.skuId)
            UInt64Value.internalBinaryWrite(message.skuId, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* optional google.protobuf.Timestamp expires_at = 4; */
        if (message.expiresAt)
            Timestamp.internalBinaryWrite(message.expiresAt, writer.tag(4, WireType.LengthDelimited).fork(), options).join();
        /* string label = 5; */
        if (message.label !== "")
            writer.tag(5, WireType.LengthDelimited).string(message.label);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.UserNameplate
 */
export const User_UserNameplate = new User_UserNameplate$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_UserCollectibles$Type extends MessageType<User_UserCollectibles> {
    constructor() {
        super("discord_protos.users.v1.User.UserCollectibles", [
            { no: 1, name: "nameplate", kind: "message", T: () => User_UserNameplate }
        ]);
    }
    create(value?: PartialMessage<User_UserCollectibles>): User_UserCollectibles {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<User_UserCollectibles>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_UserCollectibles): User_UserCollectibles {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional discord_protos.users.v1.User.UserNameplate nameplate */ 1:
                    message.nameplate = User_UserNameplate.internalBinaryRead(reader, reader.uint32(), options, message.nameplate);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_UserCollectibles, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional discord_protos.users.v1.User.UserNameplate nameplate = 1; */
        if (message.nameplate)
            User_UserNameplate.internalBinaryWrite(message.nameplate, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.UserCollectibles
 */
export const User_UserCollectibles = new User_UserCollectibles$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_NormalState$Type extends MessageType<User_NormalState> {
    constructor() {
        super("discord_protos.users.v1.User.NormalState", []);
    }
    create(value?: PartialMessage<User_NormalState>): User_NormalState {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<User_NormalState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_NormalState): User_NormalState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_NormalState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.NormalState
 */
export const User_NormalState = new User_NormalState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_RestrictedState$Type extends MessageType<User_RestrictedState> {
    constructor() {
        super("discord_protos.users.v1.User.RestrictedState", [
            { no: 1, name: "restricted_until", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<User_RestrictedState>): User_RestrictedState {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<User_RestrictedState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_RestrictedState): User_RestrictedState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Timestamp restricted_until */ 1:
                    message.restrictedUntil = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.restrictedUntil);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_RestrictedState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Timestamp restricted_until = 1; */
        if (message.restrictedUntil)
            Timestamp.internalBinaryWrite(message.restrictedUntil, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.RestrictedState
 */
export const User_RestrictedState = new User_RestrictedState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_DeferredActionState$Type extends MessageType<User_DeferredActionState> {
    constructor() {
        super("discord_protos.users.v1.User.DeferredActionState", [
            { no: 1, name: "action_deferred_until", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<User_DeferredActionState>): User_DeferredActionState {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<User_DeferredActionState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_DeferredActionState): User_DeferredActionState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Timestamp action_deferred_until */ 1:
                    message.actionDeferredUntil = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.actionDeferredUntil);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_DeferredActionState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Timestamp action_deferred_until = 1; */
        if (message.actionDeferredUntil)
            Timestamp.internalBinaryWrite(message.actionDeferredUntil, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.DeferredActionState
 */
export const User_DeferredActionState = new User_DeferredActionState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_TempBannedState$Type extends MessageType<User_TempBannedState> {
    constructor() {
        super("discord_protos.users.v1.User.TempBannedState", [
            { no: 1, name: "banned_until", kind: "message", T: () => Timestamp }
        ]);
    }
    create(value?: PartialMessage<User_TempBannedState>): User_TempBannedState {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<User_TempBannedState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_TempBannedState): User_TempBannedState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* optional google.protobuf.Timestamp banned_until */ 1:
                    message.bannedUntil = Timestamp.internalBinaryRead(reader, reader.uint32(), options, message.bannedUntil);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_TempBannedState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* optional google.protobuf.Timestamp banned_until = 1; */
        if (message.bannedUntil)
            Timestamp.internalBinaryWrite(message.bannedUntil, writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.TempBannedState
 */
export const User_TempBannedState = new User_TempBannedState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_BannedState$Type extends MessageType<User_BannedState> {
    constructor() {
        super("discord_protos.users.v1.User.BannedState", []);
    }
    create(value?: PartialMessage<User_BannedState>): User_BannedState {
        const message = globalThis.Object.create((this.messagePrototype!));
        if (value !== undefined)
            reflectionMergePartial<User_BannedState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_BannedState): User_BannedState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_BannedState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.BannedState
 */
export const User_BannedState = new User_BannedState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_SafetyState$Type extends MessageType<User_SafetyState> {
    constructor() {
        super("discord_protos.users.v1.User.SafetyState", [
            { no: 101, name: "normal", kind: "message", oneof: "state", T: () => User_NormalState },
            { no: 102, name: "restricted", kind: "message", oneof: "state", T: () => User_RestrictedState },
            { no: 103, name: "deferred_action", kind: "message", oneof: "state", T: () => User_DeferredActionState },
            { no: 104, name: "temp_banned", kind: "message", oneof: "state", T: () => User_TempBannedState },
            { no: 105, name: "banned", kind: "message", oneof: "state", T: () => User_BannedState },
            { no: 1, name: "reason", kind: "enum", T: () => ["discord_protos.users.v1.User.SafetyStateReason", User_SafetyStateReason, "SAFETY_STATE_REASON_"] },
            { no: 2, name: "annotations", kind: "enum", repeat: 1 /*RepeatType.PACKED*/, T: () => ["discord_protos.users.v1.User.SafetyAnnotations", User_SafetyAnnotations, "SAFETY_ANNOTATIONS_"] },
            { no: 3, name: "last_mutation_id", kind: "message", T: () => UInt64Value }
        ]);
    }
    create(value?: PartialMessage<User_SafetyState>): User_SafetyState {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.state = { oneofKind: undefined };
        message.reason = 0;
        message.annotations = [];
        if (value !== undefined)
            reflectionMergePartial<User_SafetyState>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_SafetyState): User_SafetyState {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* discord_protos.users.v1.User.NormalState normal */ 101:
                    message.state = {
                        oneofKind: "normal",
                        normal: User_NormalState.internalBinaryRead(reader, reader.uint32(), options, (message.state as any).normal)
                    };
                    break;
                case /* discord_protos.users.v1.User.RestrictedState restricted */ 102:
                    message.state = {
                        oneofKind: "restricted",
                        restricted: User_RestrictedState.internalBinaryRead(reader, reader.uint32(), options, (message.state as any).restricted)
                    };
                    break;
                case /* discord_protos.users.v1.User.DeferredActionState deferred_action */ 103:
                    message.state = {
                        oneofKind: "deferredAction",
                        deferredAction: User_DeferredActionState.internalBinaryRead(reader, reader.uint32(), options, (message.state as any).deferredAction)
                    };
                    break;
                case /* discord_protos.users.v1.User.TempBannedState temp_banned */ 104:
                    message.state = {
                        oneofKind: "tempBanned",
                        tempBanned: User_TempBannedState.internalBinaryRead(reader, reader.uint32(), options, (message.state as any).tempBanned)
                    };
                    break;
                case /* discord_protos.users.v1.User.BannedState banned */ 105:
                    message.state = {
                        oneofKind: "banned",
                        banned: User_BannedState.internalBinaryRead(reader, reader.uint32(), options, (message.state as any).banned)
                    };
                    break;
                case /* discord_protos.users.v1.User.SafetyStateReason reason */ 1:
                    message.reason = reader.int32();
                    break;
                case /* repeated discord_protos.users.v1.User.SafetyAnnotations annotations */ 2:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.annotations.push(reader.int32());
                    else
                        message.annotations.push(reader.int32());
                    break;
                case /* optional google.protobuf.UInt64Value last_mutation_id */ 3:
                    message.lastMutationId = UInt64Value.internalBinaryRead(reader, reader.uint32(), options, message.lastMutationId);
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_SafetyState, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* discord_protos.users.v1.User.SafetyStateReason reason = 1; */
        if (message.reason !== 0)
            writer.tag(1, WireType.Varint).int32(message.reason);
        /* repeated discord_protos.users.v1.User.SafetyAnnotations annotations = 2; */
        if (message.annotations.length) {
            writer.tag(2, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.annotations.length; i++)
                writer.int32(message.annotations[i]);
            writer.join();
        }
        /* optional google.protobuf.UInt64Value last_mutation_id = 3; */
        if (message.lastMutationId)
            UInt64Value.internalBinaryWrite(message.lastMutationId, writer.tag(3, WireType.LengthDelimited).fork(), options).join();
        /* discord_protos.users.v1.User.NormalState normal = 101; */
        if (message.state.oneofKind === "normal")
            User_NormalState.internalBinaryWrite(message.state.normal, writer.tag(101, WireType.LengthDelimited).fork(), options).join();
        /* discord_protos.users.v1.User.RestrictedState restricted = 102; */
        if (message.state.oneofKind === "restricted")
            User_RestrictedState.internalBinaryWrite(message.state.restricted, writer.tag(102, WireType.LengthDelimited).fork(), options).join();
        /* discord_protos.users.v1.User.DeferredActionState deferred_action = 103; */
        if (message.state.oneofKind === "deferredAction")
            User_DeferredActionState.internalBinaryWrite(message.state.deferredAction, writer.tag(103, WireType.LengthDelimited).fork(), options).join();
        /* discord_protos.users.v1.User.TempBannedState temp_banned = 104; */
        if (message.state.oneofKind === "tempBanned")
            User_TempBannedState.internalBinaryWrite(message.state.tempBanned, writer.tag(104, WireType.LengthDelimited).fork(), options).join();
        /* discord_protos.users.v1.User.BannedState banned = 105; */
        if (message.state.oneofKind === "banned")
            User_BannedState.internalBinaryWrite(message.state.banned, writer.tag(105, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.SafetyState
 */
export const User_SafetyState = new User_SafetyState$Type();
// @generated message type with reflection information, may provide speed optimized methods
class User_DisplayNameStyles$Type extends MessageType<User_DisplayNameStyles> {
    constructor() {
        super("discord_protos.users.v1.User.DisplayNameStyles", [
            { no: 1, name: "font_id", kind: "enum", T: () => ["discord_protos.users.v1.User.DisplayNameFont", User_DisplayNameFont, "DISPLAY_NAME_FONT_"] },
            { no: 2, name: "effect_id", kind: "enum", T: () => ["discord_protos.users.v1.User.DisplayNameEffect", User_DisplayNameEffect, "DISPLAY_NAME_EFFECT_"] },
            { no: 3, name: "colors", kind: "scalar", repeat: 1 /*RepeatType.PACKED*/, T: 13 /*ScalarType.UINT32*/ }
        ]);
    }
    create(value?: PartialMessage<User_DisplayNameStyles>): User_DisplayNameStyles {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.fontId = 0;
        message.effectId = 0;
        message.colors = [];
        if (value !== undefined)
            reflectionMergePartial<User_DisplayNameStyles>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: User_DisplayNameStyles): User_DisplayNameStyles {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* discord_protos.users.v1.User.DisplayNameFont font_id */ 1:
                    message.fontId = reader.int32();
                    break;
                case /* discord_protos.users.v1.User.DisplayNameEffect effect_id */ 2:
                    message.effectId = reader.int32();
                    break;
                case /* repeated uint32 colors */ 3:
                    if (wireType === WireType.LengthDelimited)
                        for (let e = reader.int32() + reader.pos; reader.pos < e;)
                            message.colors.push(reader.uint32());
                    else
                        message.colors.push(reader.uint32());
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: User_DisplayNameStyles, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* discord_protos.users.v1.User.DisplayNameFont font_id = 1; */
        if (message.fontId !== 0)
            writer.tag(1, WireType.Varint).int32(message.fontId);
        /* discord_protos.users.v1.User.DisplayNameEffect effect_id = 2; */
        if (message.effectId !== 0)
            writer.tag(2, WireType.Varint).int32(message.effectId);
        /* repeated uint32 colors = 3; */
        if (message.colors.length) {
            writer.tag(3, WireType.LengthDelimited).fork();
            for (let i = 0; i < message.colors.length; i++)
                writer.uint32(message.colors[i]);
            writer.join();
        }
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message discord_protos.users.v1.User.DisplayNameStyles
 */
export const User_DisplayNameStyles = new User_DisplayNameStyles$Type();
