name: Mark stale issues and pull requests

on:
  schedule:
    - cron: '0 12,0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write

    steps:
      - uses: actions/stale@v5
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

          stale-issue-message: "This issue has been marked as stale due to inactivity. If no further activity occurs, it will be closed in 14 days."
          stale-pr-message: "This pull request has been marked as stale due to inactivity. If no further activity occurs, it will be closed in 14 days."
          close-issue-message: "Closing this issue due to prolonged inactivity. Feel free to reopen if needed."
          close-pr-message: "Closing this pull request due to prolonged inactivity. Reopen if you plan to continue working on it."

          stale-issue-label: "stale"
          stale-pr-label: "stale-pr"
          exempt-issue-labels: "important, help-wanted, in-progress"
          exempt-pr-labels: "in-progress, review-needed"

          days-before-stale: 30
          days-before-close: 14
          days-before-pr-close: 14

          remove-stale-when-updated: true
